[package]
name = "incarnation"
version = "0.1.0"
authors = ["Hunter Praska <hunter@wiggin-labs.com>"]

[dependencies]
regex = "1.0.6"
lazy_static = "1.2.0"
derive_is_enum_variant = "0.1.1"
string-interner = "0.7.0"
