[package]
name = "tokenizer"
version = "0.1.0"
authors = ["Hunter Praska <hunter@wiggin-labs.com>"]

[dependencies]
string-interner = "0.7.1"
lazy_static = "1.4.0"
regex = "1.3.1"
derive_is_enum_variant = "0.1.1"
