[package]
name = "amd64"
version = "0.1.0"
authors = ["Hunter Praska <hunter@wiggin-labs.com>"]
#build = "build.rs"

#[build-dependencies.parser]
#path = "../parser"

[dependencies]
byteorder = "1.2.6"

[dependencies.asm-syntax]
path = "../asm-syntax"
